### ISSUE TITLE
How to use this one?

### ISSUE THREAD

**Issue by ghost** [minhhh/UBootstrap.Webp#1]
hi, i download your project and opened in unity 5.4.3 same version of yours;
however when i try to play, it's come with error:
DllNotFoundException: webp
WebP.Texture2DExt.GetWebPDimensions (System.Byte[] lData, System.Int32& lWidth, System.Int32& lHeight) (at Assets/WebP/Plugins/WebP/Texture2DExt.cs:85)
WebP.Texture2DExt.CreateTexture2DFromWebP (System.Byte[] lData, Boolean lMipmaps, Boolean lLinear, WebP.Status& lError, WebP.ScalingFunction scalingFunction) (at Assets/WebP/Plugins/WebP/Texture2DExt.cs:188)

any idea?

**Comment by minhhh** [comment]
Hi, this was caused by a typo. The lib's name is supposed to be libwebp not webp. I've fixed this in the latest commit. Let me know if you still encounter the error.

**Comment by ghost** [comment]
it's works now.

thx.


________________________________
寄件者: Ha.Minh <notifications@github.com>
寄件日期: 2017年6月7日 上午 09:16
收件者: minhhh/UBootstrap.Webp
副本: zhyrao; Author
主旨: Re: [minhhh/UBootstrap.Webp] How to use this one? (#1)


Hi, this was caused by a typo. The lib's name is supposed to be libwebp not webp. I've fixed this in the latest commit. Let me know if you still encounter the error.
