### ISSUE TITLE
Convert PNG to webp?

### ISSUE THREAD

**Issue by ghost** [minhhh/UBootstrap.Webp#2]
Hi, minhhh,
I am confused about how to use webp on project.
Basically is i need to convert Png to webp in unity, no idea about how to do it?
Help plz;
:)

**Comment by minhhh** [comment]
You don't convert png to webp in Unity, you convert it using cwebp from google: https://developers.google.com/speed/webp/docs/using. After you have the .bytes file, you can drag it into Unity Assets to use

**Comment by ghost** [comment]
well, that's means that i can not convert PNG to WEBP format by coding?

Sad...


________________________________
寄件者: Ha.Minh <notifications@github.com>
寄件日期: 2017年6月8日 上午 11:23
收件者: minhhh/UBootstrap.Webp
副本: zhyrao; Author
主旨: Re: [minhhh/UBootstrap.Webp] Convert PNG to webp? (#2)


You don't convert png to webp in Unity, you convert it using cwebp from google: https://developers.google.com/speed/webp/docs/using. After you have the .bytes file, you can drag it into Unity Assets to use

Getting Started | WebP | Google Developers<https://developers.google.com/speed/webp/docs/using>
developers.google.com
Image enthusiasts should use one of the many software products that support WebP. Such products include Pixelmator, ImageMagick, GIMP, Leptonica and ...

**Comment by minhhh** [comment]
What do you mean by that? 
Do you need to convert png to webp using Unity? Why?
Or do you just need a tool to convert png to webp using any language?

**Comment by ghost** [comment]
What I need is to convert png or jpg to webp in unity when app is running, rather than a tool to convert it then used in unity.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ha.Minh<mailto:notifications@github.com>
发送时间: 2017年6月9日 16:43
收件人: minhhh/UBootstrap.Webp<mailto:UBootstrap.Webp@noreply.github.com>
抄送: zhyrao<mailto:rain330047@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [minhhh/UBootstrap.Webp] Convert PNG to webp? (#2)


What do you mean by that?
Do you need to convert png to webp using Unity? Why?
Or do you just need a tool to convert png to webp using any language?

―

**Comment by minhhh** [comment]
I see. In that case you can write a bit of code to convert RGBA to webp using the libwebp library that's already included. You can create Texture2D and read png, jpg from the file system.

**Comment by ghost** [comment]
thx, already solve it.
